server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d9nq1rjncjis73an65i0-a.oregon-postgres.render.com:5432/absherondb
spring.datasource.username=absheron_user
spring.datasource.password=UImsVxeeoo22RuwN1hPOtFjUq2NnmZZb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true