# PostgreSQL connection via Render Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d9nq1rjncjis73an65i0-a:5432/absherondb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:absheron_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:UImsVxeeoo22RuwN1hPOtFjUq2NnmZZb}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Render Port Binding
server.port=${PORT:8080}