# ??????????? ? PostgreSQL ?? Render
spring.datasource.url=jdbc:postgresql://dpg-d9nq1rjncjis73an65i0-a:5432/absherondb
spring.datasource.username=absheron_user
spring.datasource.password=UImsVxeeoo22RuwN1hPOtFjUq2NnmZZb
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true